# .github/workflows/ci.yml
name: CI Check
on:
  push: { branches: [ "main" ] }
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }
      - run: npm ci
      - name: Type check (logs only)
        run: npm run typecheck || true     # 失敗してもジョブ続行
      - name: Rules test (logs only)
        run: npx firebase-tools emulators:exec --only firestore "npx vitest run src/rules.test.ts" || true
