name: CI Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      # 型 + ルールテスト（Emuを自動起動してから実行）
      - name: Run checks
        run: |
          npm run typecheck
          npx firebase-tools emulators:exec --only firestore "npx vitest run src/rules.test.ts"